name: des_plugin_example
description: Demonstrates how to use the des_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  des_plugin:
    path: ../
flutter:
  uses-material-design: true
  