name: des_plugin
description: Des and 3des encryption and decryption
version: 0.0.6
homepage: https://github.com/umair599/flutter_des_plugin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pensoon.des_plugin
    pluginClass: DesPlugin
